[package]
name = "keccak256-metal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metal = "0.27.0"
solana-sdk = "1.18.11"
tiny-keccak = {version ="2.0.2",  features = ["keccak"]} 

