[package]
name = "keccak256-metal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logfather = "0.2.5"
metal = "0.27.0"
solana-program = "1.18.11"
solana-sdk = "1.18.11"

